### ISSUE TITLE
Refactoring the Connection Model, Settings Model and Connection Handler

### ISSUE THREAD

**Issue by Qv2ray-dev** [Qv2ray/Qv2ray#353]
Refactor the mainwindow contains these steps:

- [x] Frontend-backend separation
- [x] Use Model instead of Item Viewer
- [ ] New `Connection Handler` for handling all connection-related events, e.g:
    - [x] Connect
    - [x] DisConnect
    - [ ] Rename
    - [x] Delete
    - [ ] Duplicate
    - [x] Grouping
    - [x] Share
    - [x] Reload

**Comment by Qv2ray-dev** [comment]
This will be released together with Qv2ray v2.2 or v2.3

**Comment by Qv2ray-dev** [comment]
This new version of Qv2ray will use UUIDs to manage ALL connections, this can eliminate ALL file path checkers and prevent renaming issues.

**Comment by Qv2ray-dev** [comment]
**Upgrading Qv2ray v1.* directly up to Qv2ray v2.2/2.3 is now becoming an unsupported operation.**

Users should **firstly** use Qv2ray v2.0/2.1 to upgrade their configuration to a more recent version.
Then try the newest version.

**Comment by Qv2ray-dev** [comment]
### Upgrading Qv2ray v1.* directly up to Qv2ray v2.2/2.3 is now unsupported.
 
Users should firstly use Qv2ray v2.0/2.1 to upgrade their configuration to a more recent version. 
Then try the newest version.

**Comment by William1204** [comment]
我有个问题，就是设置PAC连接时，youtube 可以播放，而封面却无法加载，why，是我的设置问题吗？我在win10 和 ubuntu 上都遇到了这个问题

**Comment by DuckSoft** [comment]
@William1204 这个问题应该是上游 PAC 的问题。这个问题已经多次出现，我们决定调查一下。

**Comment by Qv2ray-dev** [comment]
https://github.com/k06a/boolinq

**Comment by Qv2ray-dev** [comment]
TODO need more checks here https://github.com/Qv2ray/Qv2ray/blob/3f265bb8a98334ad8b31e87ede1b497db5ef193f/src/ui/widgets/ConnectionWidget.hpp#L58

**Comment by Qv2ray-dev** [comment]
https://developercommunity.visualstudio.com/content/problem/93889/error-c2872-byte-ambiguous-symbol.html

**Comment by DuckSoft** [comment]
This also only happens if "using namespace std;" is declared BEFORE the offending Windows header.

**Comment by Qv2ray-dev** [comment]
done
